---
- hosts: local
  roles:
    - { role: alacritty, tags: ["alacritty"] }
    - { role: sway, when: ansible_os_family != 'Darwin', tags: ["sway"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: vim, tags: ["vim"] }
    - { role: zsh, tags: ["zsh"] }