- name: Stop WirePlumber user service.
  ansible.builtin.systemd:
    name: wireplumber
    state: stopped
    scope: user

- name: Copy wallpapers to the configuration directory
  wireplumber_volume:
    app_name: "{{ item.app_name }}"
    description: "{{ item.description }}"
    volume: "{{ item.volume }}"
  with_items:
    - { app_name: "Diablo IV", volume: 0.048483, description: "Diablo IV" }
    - { app_name: "Fallout 76", volume: 0.120154, description: "Fallout 76" }
    - { app_name: "World of Warcraft", volume: 0.070622, description: "World of Warcraft" }
    - { app_name: "FMOD Ex App", volume: 0.091829, description: "RimWorld, Terra Nile, and other games" }
    - { app_name: "Firefox", volume: 0.1, description: "Firefox Browser" }

- name: Start WirePlumber user service.
  ansible.builtin.systemd:
    name: wireplumber
    state: started
    scope: user