---
- name: Generating .zshrc
  ansible.builtin.template:
    src: "templates/zshrc.j2"
    dest: "~/.zshrc"
    mode: u=rw,g=r,o=

- name: Generating .profile
  ansible.builtin.template:
    src: "templates/profile.j2"
    dest: "~/.profile"
    mode: u=rw,g=r,o=