- name: Ensure the acl package is included to be able to let Ansible get an unprivileged user.
  become: yes
  ansible.builtin.apt:
    name: acl
    state: present

- name: Ensure zsh and some requirements are installed on the computer.
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bat
    - direnv
    - fzf
    - git
    - tig
    - wget
    - zsh