- name: Ensure the acl package is included to be able to let Ansible get an unprivileged user.
  ansible.builtin.pacman:
    name: acl
    state: present

- name: Ensure zsh is installed on the computer.
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - zsh
    - fzf
    - direnv