- name: Ensure zsh and some requirements are installed on the computer.
  ansible.builtin.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - direnv
    - fzf
    - git
    - tig
    - zsh