- name: Ensure the acl package is included to be able to let Ansible get an unprivileged user.
  ansible.builtin.apt:
    name: acl
    state: present

- name: Ensure tmux is installed on the computer.
  ansible.builtin.apt:
    name: tmux
    state: present
