users_to_configure: "{{ vault_users_to_configure }}"
zsh_kerberos_username: "{{ vault_zsh_kerberos_username }}"

sway_wayland_window_rules:
  - name: "Adlié-based applications"
    app_id: "adelie"
    flags:
      - max_render_time off
      - floating enabled
      - move window to output $output-primary
      - blur disabled

  - name: "NextCloud Desktop Client"
    app_id: "com.nextcloud.desktopclient.nextcloud"
    flags:
      - floating enabled
      - resize set width 500px
      - resize set height 600px
      - move window position 80 ppt 0 ppt

  - name: "Alacritty Terminal Emulator"
    app_id: "Alacritty"
    flags:
      - workspace $ws-primary-terminal

  - name: "Firefox Browser"
    app_id: "firefox"
    flags:
      - workspace $ws-browser

  - name: "Valve GameScope Wrapper for Games"
    app_id: "gamescope"
    flags:
      - move window to output $output-primary

sway_x11_window_rules:
  - name: "Video LAN Client"
    class: "vlc"
    flags:
      - floating enabled

  - name: "JetBrains Toolbox"
    class: "jetbrains-toolbox"
    flags:
      - floating enabled
      - resize set width 500px
      - resize set height 600px
      - move window position 80 ppt 0 ppt

  - name: "Steam Webbrowser"
    instance: "steamwebhelper"
    flags:
      - workspace $ws-steam
      - floating enabled
      - max_render_time off
      - blur disabled

  - name: "Spotify"
    class: "Spotify"
    flags:
      - workspace $ws-music

  - name: "RustRover IDE"
    class: "jetbrains-rustrover"
    flags:
      - workspace $ws-dev-1

  - name: "PyCharm IDE"
    class: "jetbrains-pycharm"
    flags:
      - workspace$ws-dev-1

  - name: "CLion IDE"
    class: "jetbrains-clion"
    flags:
      - workspace $ws-dev-1

  - name: "DataGrip IDE"
    class: "jetbrains-datagrip"
    flags:
      - workspace $ws-dev-2

  - name: "SpeedCrunch"
    class: "SpeedCrunch"
    flags:
      - floating enable

  - name: "Steam Client"
    class: "steam"
    flags:
      - workspace $ws-steam
      - floating disable
      - fullscreen enable
      - max_render_time off
      - blur disabled

  - name: "Baldur's Gate 3"
    class: "steam_app_1086940"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "The King is Watching"
    class: "steam_app_2753900"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Widget Inc."
    class: "steam_app_3184110"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Dwarf Fortress"
    class: "dwarfort"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Firewatch"
    class: "fw.x86_64"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Factorio"
    class: "factorio"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "FTL: Faster Then Light"
    class: "FTL.amd64"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Graveyard Keeper"
    class: "Graveyard Keeper.x86_64"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Oxygen Not Included"
    class: "OxygenNotIncluded"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Project Hospital"
    class: "ProjectHospital.x86_64"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Project Zomboid"
    class: "Project Zomboid"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Rim World"
    class: "RimWorldLinux"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Valheim"
    class: "valheim.x86_64"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

  - name: "Stardeus"
    class: "Stardeus"
    flags:
      - inhibit_idle focus
      - floating enable
      - max_render_time off
      - move window to output $output-primary
      - blur disabled

zsh_aliases:
  - name: "Add (part of) files to the git staging area"
    alias: "gap"
    command: "git add -p"

  - name: "Remove (parts of) files from the local changes"
    alias: "gcp"
    command: "git checkout -p"

  - name: "Show the status of the current repository"
    alias: "gits"
    command: "git status"

  - name: "Show the content of the last commit"
    alias: "gshow"
    command: "git show -w --word-diff"

  - name: "Show a simplified look view of the repository in the current directory"
    alias: "glook"
    command: "git log --graph --pretty=tformat:'%Cred%h%Creset (%Cgreen%cd%Creset, %C(bold blue)%an%Creset): %s%C(yellow)%d%Creset' --date=format:'%d.%m. %H%M' --abbrev-commit"

  - name: "Go to the root folder of the repository in the current directory"
    alias: "groot"
    command: "cd `git rev-parse --show-toplevel`"

  - name: "Show a TUI to view the history of the repository in the current directory"
    alias: "tigger"
    command: "tig --all"

  - name: "Show the unstaged changes without whitespaces for the repository in the current directory"
    alias: "gdw"
    command: "git diff -w --word-diff"

  - name: "Show the regular unstaged changes for the repository in the current directory"
    alias: "gd"
    command: "git diff"

zsh_enable_sdkman_support: True
zsh_enable_nvm_support: True