- name: Ensure the acl package is included to be able to let Ansible get an unprivileged user.
  become: yes
  ansible.builtin.apt:
    name: acl
    state: present

- name: Ensure vim is installed on the computer.
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - exuberant-ctags
    - fzf
    - git
    - vim
