- name: Ensure the acl package is included to be able to let Ansible get an unprivileged user.
  become: yes
  ansible.builtin.pacman:
    name: acl
    state: present

- name: Ensure vim is not installed in parallel to neoVim.
  become: yes
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: absent
  with_items:
    - vim

- name: Ensure neoVim and some additional tools are installed on the computer.
  become: yes
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - ctags
    - fzf
    - git
    - nvim